# Generated by Django 4.2.3 on 2023-08-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='imagen',
        ),
    ]
