# Generated by Django 4.2.7 on 2023-12-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
