# Generated by Django 4.2.3 on 2023-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_alter_modulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default=1, upload_to='cateoria_imagen/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulo',
            name='imagen',
            field=models.ImageField(upload_to='modulos_imagen/'),
        ),
    ]
