# Generated by Django 4.2.3 on 2023-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_modulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Pictograma')], max_length=250),
        ),
    ]
