# Generated by Django 4.2.3 on 2023-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_alter_modulo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadpictogramas',
            old_name='nombrepictograma',
            new_name='descripcion_pictograma',
        ),
        migrations.RenameField(
            model_name='actividadpictogramas',
            old_name='imagen',
            new_name='imagen_pictograma',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[(1, 'Pictograma')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadpictogramas',
            name='nombre_pictograma',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
