# Generated by Django 4.2.3 on 2023-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_rename_nombrepictograma_actividadpictogramas_descripcion_pictograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadpictogramas',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
