# Generated by Django 4.2.7 on 2023-12-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Persona',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadordenaroracion',
            options={'verbose_name_plural': 'Actividades Ordenar Oraciones'},
        ),
        migrations.AlterModelOptions(
            name='actividadpictogramas',
            options={'verbose_name_plural': 'Actividades Pictogramas'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='resulatadosactividad',
            options={'verbose_name_plural': 'Resultados de Actividades'},
        ),
    ]
