# Generated by Django 4.2.3 on 2023-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_alter_actividadpictogramas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadpictogramas',
            options={},
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[(1, 'Pictograma'), (2, 'Dibujo'), (2, 'Memoria')], max_length=250),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Pictograma'), (2, 'Dibujo'), (2, 'Memoria')], max_length=250),
        ),
    ]
