# Generated by Django 4.2.3 on 2023-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_alter_actividadpictogramas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='modulos_imagen/'),
            preserve_default=False,
        ),
    ]
