# Generated by Django 4.2.3 on 2023-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_remove_actividadpictogramas_nombre_pictograma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadpictogramas',
            name='orden',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
