# Generated by Django 4.2.3 on 2023-10-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0013_alter_actividadpictogramas_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadpictogramas',
            name='descripcion_pictograma',
        ),
    ]
