# Generated by Django 4.2.3 on 2023-10-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0014_remove_actividadpictogramas_descripcion_pictograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadpictogramas',
            name='orden',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
