# Generated by Django 4.2.7 on 2023-11-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0015_alter_actividadpictogramas_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
