# Generated by Django 4.2.7 on 2023-11-19 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0016_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadOrdenarOracion',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulos.actividad')),
            ],
            bases=('modulos.actividad',),
        ),
        migrations.CreateModel(
            name='frases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='frases_imagen/')),
            ],
        ),
        migrations.DeleteModel(
            name='ActividadOrdenarPalabras',
        ),
        migrations.AddField(
            model_name='actividadordenaroracion',
            name='frases',
            field=models.ManyToManyField(blank=True, to='modulos.frases'),
        ),
    ]
