# Generated by Django 4.2.7 on 2023-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0017_actividadordenaroracion_frases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadordenaroracion',
            name='frases_ordenadas',
            field=models.ManyToManyField(blank=True, related_name='frases_ordenadas', to='modulos.frases'),
        ),
        migrations.AddField(
            model_name='actividadordenaroracion',
            name='imagen_ordenar',
            field=models.ImageField(blank=True, null=True, upload_to='actividad_imagen/'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('PIC', 'Pictograma'), ('DIB', 'Dibujo'), ('MEM', 'Memoria'), ('', 'Ordenar Oración')]),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[('PIC', 'Pictograma'), ('DIB', 'Dibujo'), ('MEM', 'Memoria'), ('', 'Ordenar Oración')]),
        ),
    ]
