# Generated by Django 4.2.7 on 2023-11-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0018_actividadordenaroracion_frases_ordenadas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frases',
            new_name='Frase',
        ),
    ]
