# Generated by Django 4.2.7 on 2023-11-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0020_actividadordenaroracion_frase_original_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadordenaroracion',
            old_name='oracion',
            new_name='oracionn',
        ),
    ]
