# Generated by Django 4.2.7 on 2023-11-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0021_rename_oracion_actividadordenaroracion_oracionn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadordenaroracion',
            old_name='oracionn',
            new_name='frase_original',
        ),
    ]
