# Generated by Django 4.2.7 on 2023-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0023_rename_frase_original_actividadordenaroracion_oracion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frase',
            new_name='Palabra',
        ),
        migrations.RenameField(
            model_name='actividadordenaroracion',
            old_name='frases',
            new_name='palabras',
        ),
        migrations.RemoveField(
            model_name='actividadordenaroracion',
            name='frases_ordenadas',
        ),
    ]
