# Generated by Django 4.2.7 on 2023-11-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0024_rename_frase_palabra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='texto',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
