# Generated by Django 4.2.7 on 2023-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0027_alter_actividadordenaroracion_palabras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadordenaroracion',
            name='palabras',
            field=models.ManyToManyField(blank=True, to='modulos.palabra'),
        ),
    ]
